---
 #Intervall
Save_Intervall:
  INTERVALL: !!python/int 1

 #Time Set
Time:
  LOCATION: !!python/str 'Europe/Berlin'

#USB BACKUP FOLDER
USB_FOLDER:
  STATUS: !!python/bool False

#BackupExertn
Backup_Extern:
  SERVER_IP: !!python/str '217.160.59.243'
  SERVER_PORT: !!python/int 8086
  USERNAME: !!python/str root
  SERVER_PW: !!python/str 'jmb8OuH2#u'
  DATABASE_NAME: !!python/str 'Backup_Data'
  MEASUREMEMT_NAME: !!python/str 'Data'
  NUMBER_OF_BACKUPS:

Backup_Local:
  SERVER_IP: !!python/str localhost
  SERVER_PORT: !!python/int 8086
  USERNAME: !!python/str python
  SERVER_PW: !!python/str 'Pyth0n'
  DATABASE_NAME: !!python/str 'Backup_Data'
  MEASUREMEMT_NAME: !!python/str 'Data'
  NUMBER_OF_BACKUPS:


#Notifications
Notifications:
  STATUS: FALSE
  NOTIFICATIONS_INTERVAL: !!python/int 10 #in Sekunden


#Retention-Policy Parameter
Retention:
  retention_name : !!python/str test_retention
  retention_duration : !!python/str 10h
  shard_duration : !!python/str 1h

#Continuous-Query Parameter
Query:
  query_name : !!python/str power_grid_mean
  original_data : !!python/str power_grid
  data : !!python/str value
  mean_time : !!python/str 15m
  sample_time : !!python/str 1m
  q_duration : !!python/str 1000w

